### ISSUE TITLE
create demo with maximum size in browser window

### ISSUE THREAD

**Issue by ngehlenborg** [hms-dbmi/4DN_matrix-viewer#1]
We need a demo that has a larger view (also for testing performance when more pixels have to be rendered). I would recommend that we create a second demo in addition to the existing one that just has a view (or two!) that use the maximum available space within the current browser window (resize views upon resize of the browser window).

@pkerpedjiev - any other features we might want to add here? I think the debug mode should be accessible as well.

**Comment by Alaleh1191** [comment]
We found two different ways to create resizable demos, they are in the following branches:
"vanilla-Nikhil" and "resizable".
